### ISSUE TITLE
How to add digital filter?

### ISSUE THREAD

**Issue by rmond18** [atomic14/esp32-walkie-talkie#2]
Hi, thank you so much for your work. It's awesome, I'm planning to add low pass filter to remove the ambient/jittering noise, but I'm only a beginner and I'm not sure how and where to add the code for this. I don't have any idea how to start. If you could just point me in the right direction, maybe I'd manage.

Thank you again, keep up the good work!

**Comment by cgreening** [comment]
Hi there, I had a look at this when I was playing around with the noise issues.

As always, there's a couple of options :)

There are some nice tools that you can use to build the code for the actual filter - this seems to be a good one - http://t-filter.engineerjs.com/

The code they generate tends to be pretty similar. You push new samples into the filter and you pull out the current value.

In my code there's quite a convenient place to do this - `lib/transport/src/Tansport.cpp`- has a function:

```
void add_sample(int16_t sample)
```

This would probably be a good place to do it as it is the single place where samples are pushed into a buffer before being sent out.
