### ISSUE TITLE
Button ,?

### ISSUE THREAD

**Issue by sbabadag** [atomic14/esp32-walkie-talkie#23]
Hi I have connected all the parts but I couldnt understand the connection of the transmit button :( can you explain pls thanks for this great project.

**Comment by cgreening** [comment]
Saw your comment on YouTube - is the question which pins to connect the button to?

In you look in `config.h` there's a define for it:

```
#define GPIO_TRANSMIT_BUTTON 23
```

So you need to connect one side of the button to pin 23.

The other side of the button should be connected to 3.3v
